[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@abdk/=lib/abdk-libraries-solidity/",
    "@chainlink/=lib/chainlink-brownie-contracts/"
]
build_info = true
cache_path = "cache"
optimizer_runs = 200
solc_version = "0.8.24"
ffi = true
ast = true
extra_output = ["storageLayout"]
